version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  pg_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db-setup/app-db:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onelab_db
      - POSTGRES_USER=onelab
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onelab -d onelab_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=dev
      - JWT_KEY=qwerty
      - TZ=Asia/Almaty
      - PG_HOST=postgres
      - PG_NAME=onelab_db
      - PG_USER=onelab
      - PG_PASSWORD=qwerty
      - PG_PORT=5432
    networks:
      - internal
    depends_on:
      - postgres
      - redis

  postgres-transaction:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db-setup/transaction-db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=onelab_db
      - POSTGRES_USER=onelab
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onelab -d onelab_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction:
    image: zhaisanbay/transaction-service:onelab
    restart: always
    ports:
      - "8081:8081"
    environment:
      - APP_MODE=dev
      - JWT_KEY=qwerty
      - TZ=Asia/Almaty
      - DB_HOST=postgres
      - DB_NAME=onelab_db
      - DB_USER=onelab
      - DB_PASSWORD=qwerty
      - DB_PORT=5432
    networks:
      - internal
    depends_on:
      - app
      - postgres-transaction


  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379:6379"
