version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  pg_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    networks:
      - internal
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  migration:
    image: migrate/migrate
    command: -path ./internal/storage/postgres/migrations/ -database 'postgres://onelab:qwerty@localhost:5432/onelab_db?sslmode=disable' up
    depends_on:
      - postgres

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=${APP_MODE}
      - APP_PORT=${APP_PORT}
      - JWT_KEY=${JWT_KEY}
      - TZ=Asia/Almaty
      - PG_HOST=postgres
      - PG_NAME=${PG_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    networks:
      - internal
    depends_on:
      - postgres
      - migration
      - redis

  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379:6379"