basePath: /local/db
definitions:
  model.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
    type: object
  model.Transaction:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  model.TransactionItem:
    properties:
      ID:
        type: integer
      book:
        $ref: '#/definitions/model.Book'
      transactionID:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: Transaction microservice.
  termsOfService: http://swagger.io/terms/
  title: OneLab HomeWork API
  version: "1.0"
paths:
  /transaction/{id}:
    delete:
      description: delete transaction with items from db
      operationId: delete-transaction
      parameters:
      - description: transactionID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: delete transaction
      tags:
      - transaction
  /transactions:
    post:
      consumes:
      - application/json
      description: create transaction
      operationId: create-transaction
      parameters:
      - description: transaction date
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Transaction'
      responses:
        "200":
          description: OK
          schema:
            type: int
        "400":
          description: ""
        "500":
          description: ""
      summary: Create transaction
      tags:
      - transaction
  /transactions/items:
    post:
      consumes:
      - application/json
      description: create transaction items
      operationId: create-transactionItem
      parameters:
      - description: transaction item date
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.TransactionItem'
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      summary: Create transaction item
      tags:
      - transaction
swagger: "2.0"
